CREATE TABLE "admins" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255),
	"email" varchar(255),
	"password" text,
	"onetime_key" varchar(255),
	"remember_token" text,
	"login_locked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"activated_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"terminated_at" timestamp with time zone,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "inhouse_developments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "inhouse_developments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"category" varchar(255),
	"title" varchar(255),
	"content" text,
	"inhouse_developments_image_url" varchar(255),
	"inhouse_developments_home_page_url" varchar(255),
	"status" smallint DEFAULT 1 NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "newses" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "newses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255),
	"content" text,
	"news_image_url_1" varchar(255),
	"news_image_url_2" varchar(255),
	"news_image_url_3" varchar(255),
	"status" smallint DEFAULT 1 NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone,
	"deleted_at" timestamp with time zone
);
