import { bigint, pgTable, smallint, text, timestamp, varchar } from "drizzle-orm/pg-core";

/**
 * Drizzle スキーマ（Neon / PostgreSQL）。
 * 現行 MySQL（database/migrations/*.php の生 SQL）からの変換:
 *
 * | MySQL                                   | PostgreSQL（ここ）                          |
 * |-----------------------------------------|---------------------------------------------|
 * | BIGINT(20) UNSIGNED AUTO_INCREMENT      | bigint GENERATED BY DEFAULT AS IDENTITY     |
 * | TINYINT(1) status（0/1）                | smallint（値はそのまま 0/1。管理画面の in(0,1) 検証を維持） |
 * | DATETIME DEFAULT CURRENT_TIMESTAMP      | timestamptz DEFAULT now()                   |
 * | DATETIME ON UPDATE CURRENT_TIMESTAMP    | Drizzle の $onUpdate（アプリ側で now を入れる）|
 * | COMMENT '...'                           | この JSDoc / 行コメントに残す                |
 * | utf8mb4_unicode_ci                      | DB 既定（UTF8）。照合順序の指定は不要        |
 *
 * 日時は timestamptz（UTC 保存）にし、表示整形（"YYYY年MM月DD日"）は src/lib/dates.ts で JST に変換して行う。
 * 現行は config/app.php の timezone が UTC（Laravel の now() は UTC）だが、DB 既定値の CURRENT_TIMESTAMP は
 * MySQL サーバーのタイムゾーンに依存するため、既存データの壁時計値が UTC か JST かはダンプ入手時に確認する
 * （フェーズ4のデータ移行スクリプトで補正する。確認事項）。
 * 列名は現行と同一（snake_case）にして、ダンプからの移行を単純にする。
 */

const timestamptz = (name: string) => timestamp(name, { withTimezone: true, mode: "date" });

/** お知らせマスター */
export const newses = pgTable("newses", {
  /** お知らせID */
  id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
  /** タイトル */
  title: varchar("title", { length: 255 }),
  /** 内容 */
  content: text("content"),
  /** 商品画像URL1〜3（現行のコメントのまま。実際はお知らせ画像） */
  news_image_url_1: varchar("news_image_url_1", { length: 255 }),
  news_image_url_2: varchar("news_image_url_2", { length: 255 }),
  news_image_url_3: varchar("news_image_url_3", { length: 255 }),
  /** 公開ステータス 0: 非公開, 1: 公開 */
  status: smallint("status").notNull().default(1),
  /** 備考 */
  notes: text("notes"),
  /** 登録日時 */
  created_at: timestamptz("created_at").defaultNow(),
  /** 更新日時（現行: 既定値なし、ON UPDATE のみ） */
  updated_at: timestamptz("updated_at").$onUpdate(() => new Date()),
  /** 削除日時（論理削除。手動で扱う） */
  deleted_at: timestamptz("deleted_at"),
});

/** 自社開発マスター */
export const inhouseDevelopments = pgTable("inhouse_developments", {
  /** 自社開発ID */
  id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
  /** カテゴリ */
  category: varchar("category", { length: 255 }),
  /** タイトル */
  title: varchar("title", { length: 255 }),
  /** 内容 */
  content: text("content"),
  /** 自社開発画像URL */
  inhouse_developments_image_url: varchar("inhouse_developments_image_url", { length: 255 }),
  /** 自社開発ホームページURL */
  inhouse_developments_home_page_url: varchar("inhouse_developments_home_page_url", { length: 255 }),
  /** 公開ステータス 0: 非公開, 1: 公開 */
  status: smallint("status").notNull().default(1),
  /** 備考 */
  notes: text("notes"),
  /** 登録日時 */
  created_at: timestamptz("created_at").defaultNow(),
  /** 更新日時（現行: DEFAULT CURRENT_TIMESTAMP + ON UPDATE） */
  updated_at: timestamptz("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date()),
  /** 削除日時 */
  deleted_at: timestamptz("deleted_at"),
});

/** 管理者マスター（認証はフェーズ3。テーブルだけ先に用意する） */
export const admins = pgTable("admins", {
  /** 管理者ID */
  id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
  /** 氏名 */
  name: varchar("name", { length: 255 }),
  /** メールアドレス */
  email: varchar("email", { length: 255 }),
  /** ハッシュ化パスワード（現行 bcrypt。引き継ぎ方針は §7.1 の 4） */
  password: text("password"),
  /** ログイン用ワンタイムキー（現行では無効化中。§7.1 の 5） */
  onetime_key: varchar("onetime_key", { length: 255 }),
  /** パスワード設定トークン */
  remember_token: text("remember_token"),
  /** ログインロック日時 */
  login_locked_at: timestamptz("login_locked_at"),
  /**
   * ログイン失敗回数（移行で追加）。現行はセッション内カウンタだったが Serverless では持てないため DB 列にする。
   * 成功・ロック解除時に 0 へ戻す。6 回で login_locked_at を記録（現行と同じ閾値）
   */
  login_failed_count: smallint("login_failed_count").notNull().default(0),
  /** 登録日時 */
  created_at: timestamptz("created_at").defaultNow(),
  /** 有効化日時（初期パスワード設定日時） */
  activated_at: timestamptz("activated_at"),
  /** 更新日時 */
  updated_at: timestamptz("updated_at").$onUpdate(() => new Date()),
  /** 退職日時 */
  terminated_at: timestamptz("terminated_at"),
  /** 削除日時 */
  deleted_at: timestamptz("deleted_at"),
});

export type NewsRow = typeof newses.$inferSelect;
export type NewNewsRow = typeof newses.$inferInsert;
export type InhouseDevelopmentRow = typeof inhouseDevelopments.$inferSelect;
export type AdminRow = typeof admins.$inferSelect;
